config/routes.rb
Geols::Application.routes.draw do

  root  to: 'static_pages#home'
  
  match '/contact',         to: 'static_pages#contact'
  match '/company_profile', to: 'static_pages#company_profile'
  match '/services',        to: 'static_pages#services'
  match '/news',            to: 'static_pages#news'

  match '/services/soil_investigation', to: 'static_pages#soil_investigation'
  match '/services/geotechnical_monitoring', to: 'static_pages#geotechnical_monitoring'
  match '/services/instrumentation_sales', to: 'static_pages#instrumentation_sales'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def company_profile
  end

  def services
  end

  def news
  end

  def soil_investigation
  end

  def geotechnical_monitoring
  end

  def instrumentation_sales
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">

  <div class="row-footer">
      
    <div class="span-footer">
      <h5> Quick Links </h5>
      <li><%= link_to "About",   company_profile_path %></li>
      <li><%= link_to "Services", services_path %></li>
      <li><%= link_to "News", news_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </div>

    <div class="span-footer">
      <h5> Services </h5>
      <li><%= link_to "Soil Investigation",   services_soil_investigation_path %></li>
      <li><%= link_to "Instrumentation and Monitoring", services_geotechnical_monitoring_path %></li>
      <li><%= link_to "Instrumentation Sales and Distribution", services_instrumentation_sales_path %></li>
    </div>

      <div class="span-footer">
      <h5> Affiliation </h5>
      <p><a href="http://www.itmsoil.com" target="blank">itmsoil</a></p>
      <p>SA Geolab International Pte Ltd</p>
    </div>

    <div class="span-footer">
      <h5> Location </h5>
    <address>
     <p>GeoLS Pte Ltd</p>
     <p>61 Kaki Bukit Ave 1, #04-30</p>
     <p>Shun Li Industrial Park</p>
     <p>Singapore, 417943</p>

    <p>P: +65 6546 5585</p>
    <p>F: +65 6546 5595</p>
    <p>E: <a href="mailto:admin@geols.com.sg">
        admin@geols.com.sg </a></p>
  </address>

  </div>
</div>

  <div id="copyright">
    GeoLS Pte Ltd @ Copyright 2014
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= image_tag('logo-transparent.png') %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar">
          </span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>      
    </div>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %><Home></li>
            <li><%= link_to "About GeoLS Pte Ltd", company_profile_path %></li>
            
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="<%= services_path %>"> Our Services <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="<%= services_soil_investigation_path %>">Soil Investigation</a></li>
                <li><a href="<%= services_geotechnical_monitoring_path %>">Geotechnical Instrumentation and Monitoring</a></li>
                <li><a href="<%= services_instrumentation_sales_path %>">Instrumentation Sales and Distribution</a></li>

              </ul>
            </li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "News", news_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_shim.html.erb
    	<!--[if lt IE 9]>
    	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title> GeoLS Pte Ltd | <%= yield(:title) %> </title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>

	<body>
    	<%= render 'layouts/header' %>
      	<%= yield %>
        <%= render 'layouts/footer' %>
	</body>
	
</html>

app/views/static_pages/company_profile.html.erb
<% provide(:title, 'About Us') %>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
        <li data-target="#myCarousel" data-slide-to="6"></li>
        <li data-target="#myCarousel" data-slide-to="7"></li>
      </ol>
      <div class="carousel-inner">
        
        <div class="item active">
          <img src="assets/team.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>

            </div>
          </div>
        </div>
        <div class="item">
          <img src="assets/borehole_1.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Second slide" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

        <div class="item">
          <img src="assets/marine_si.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Third slide" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

        <div class="item">
          <img src="assets/marine_si2.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Fourth slide" alt="Fourth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

        <div class="item">
          <img src="assets/borehole_2.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Fifth slide" alt="Fifth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

        <div class="item">
          <img src="assets/safety.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Sixth slide" alt="Sixth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
            </div>
          </div>
        </div>


        <div class="item">
          <img src="assets/seismic.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Seventh slide" alt="Seventh slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

        <div class="item">
          <img src="assets/terminal_box.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Eight slide" alt="Eight slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>

    <!-- /.carousel -->
<div class="container marketing">    


	<h1>Company Profile</h1>





		<p>
			GeoLS is a company specializing in Geotechnical Engineering with a wealth of experience. GeoLS's services and expertise do encompass total solution for Geotechnical Investigation, Instrumentation and Laboratory Services.

​			GeoLS was incorporated in Singapore on 29th of June 2001 Soon after the establishment, GeoLS become one 
            of the flagships in geotechnical engineering because of its quality service at reasonable price. GeoLS is a registered company of Building and Construction Authority (BCA). Detailed information of GeoLS is as per following.
		</p>
		<ul>
			<li>Business Registration : 200104293D</li>
			<li>GST Registration      : 20-0104293-D</li>
			<li>BCA Registration      : CR-15 Site Investigation Works, Specialist Builder - SB(SI)</li>
			<li>Certification         : OHSAS18001:28793/A, ISO9001:28793/B, bizSAFE STAR</li>
		</ul>

		<p>
			In under three years since its establishment in 2001, more than 100 projects were in queue for our services. This is a result of confidence and trust of customers to GeoLS services. This is exceptionally more than expected.
​		</p>
		<p>
			The first milestone project was "Geotechnical Instrumentation Worls for the New MRT Circle Line 1 Contract 825". From beginning of year 2002, million dollar projects like Kallang Paya Lebar Expressway Contract 421 and 422, Circle line Stage-2 Contract 823 are under the scope of GeoLS for geotechnical engineering services. Below is the list some of our major projects.
		</p>
		<ul>
			<li>Circle Line Stage-1: Contract-825</li>
			<li>Kallang Paya Lebar Expressway (KPE) Contract: 421 (From ECP to Nicoll Highway)</li>
			<li>Kallang Paya Lebar Expressway (KPE) Contract: 422 (From Nicoll Highway to PIE)</li>
			<li>Circle Line Stage-2: Contract-823 and 824</li>
			<li>Marina South Near Central Boulevard (Stage 2)</li>
			<li>Downtown Line 1 Contract 903</li>
			<li>Site Investigation Works for Road and Rail Project: Contract ER320</li>
		</ul>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<br />
    <div class="container marketing">
	<h1>Contact Us</h1>



	<div class="row group-contact">

		<address>
			<strong> GeoLS Pte Ltd </strong>
			<br>
			61 Kaki Bukit Ave 1, #04-30
			<br>
			Shun Li Industrial Park
			<br>
			Singapore, 417943
			<br>
			<abbr title="Phone"><i class="icon-user"></i></abbr>
			+65 6546 5585
			<br>
			<abbr title="Fax"><i class="icon-print"></i></abbr>
			+65 6546 5595
			<br>
			<abbr title="Email"><i class="icon-envelope"></i></abbr>
			<a href="mailto:admin@geols.com.sg">
			admin@geols.com.sg </a>
		</address>

		<div class="icon">
			<a href="http://facebook.com/geols.pte.ltd" target="blank">
				<img src= <%= asset_path 'facebook.png' %>> </a>
		</div>

		<div class="icon">
			<a href="#">
				<img src= <%= asset_path 'twitter.png' %>> </a>
		</div>

	</div>

	<div class="contact-map">

	<img src="//maps.googleapis.com/maps/api/staticmap?center=61+kaki+bukit+avenue+1&zoom=15&size=960x600&markers=color:blue%7Clabel:•%7C61+kaki+bukit+avenue+1&sensor=false">

	</div>
	</div>

app/views/static_pages/geotechnical_monitoring.html.erb
<% provide(:title, 'Geotechnical Instrumentation and Monitoring') %>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="assets/office.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
        </div>
        <div class="item">
          <img src="assets/bridge.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Second slide" alt="Second slide">
        </div>
        <div class="item">
          <img src="assets/tunnel.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Third slide" alt="Third slide">
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class=".glyphicon .glyphicon-chevron-left">
      </span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class=".glyphicon .glyphicon-chevron-right">
      </span>
      </a>
    </div>

	<div class="container">
		<h1>
			Geotechnical Instrumentation and Monitoring
		</h1><br/>

		<p>We provide Geotechnical Instrumentation and Monitoring from Inclinometer to Tiltmeter. We monitor the data given from the instruments to analyze the condition of the soil and structures. Our expertise includes the following:</p>

		<div class="service-list">

			<ol>
			1. Deformation of Ground and Structure Observation.
				<ul>
				<li>
					Inclinometer (Manual and Automatic)
				</li>
				<li>
					Electrolevel Sensor
				</li>
				<li>
					Tilt and Crack Meter
				</li>
				<li>
					Load Cells
				</li>
				<li>
					Settlement Marker and Plate
				</li>
				<li>
					Deep Settlement Gauge
				</li>
				<li>
					Multilevel Settlement Gauge
				</li>
				<li>
					Covergence and Divergence Measurement of Structure
				</li>
				<li>
					3D measurement of Structure and Tunnel with Automatic Systems
				</li>
				</ul>
				</ol>
		<br />
			<ol>
				2. Ground Water Observation.
				<ul>
				<li>
					Water Standpipe
				</li>
				<li>
					Peizometer
				</li>
				<li>
					Strain Gauge
				</li>
				</ul>
			</ol>
		<br />
			<ol>
				3. Monitoring Service for Construction.
				<ul>
				<li>
					Vibration Monitoring
				</li>
				<li>
					Noise Monitoring
				</li>
				</ul>
			</ol>
		<br />
			<ol>
				4. Data Management and Monitoring System.
				<ul>
				<li>
					Data Automatic Logging and Real Time Monitoring System
				</li>
				<li>
					Remote Monitoring System
				</li>
				</ul>
			</ol>

		</div>

	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>GeoLS Pte Ltd</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="assets/gls-office.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>GeoLS Pte Ltd</h1>
              <p>The specialist in soil investigation, geotechnical instrumentation and monitoring </p>

            </div>
          </div>
        </div>
        <div class="item">
          <img src="assets/itmsoil-hq.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Second slide" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Official Distributor of itmsoil</h1>
              <p>We are a part of itmsoil group, a world leader of premium quality geotechnical and structural monitoring instrumentation.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="assets/tunnel.jpg" data-src="holder.js/100%x500/auto/#777:#7a7a7a/text:Third slide" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Tunnel Monitoring and Instrumentation</h1>
              <p>We provide Instrumentation and Monitoring services.</p>
            </div>
          </div>
        </div>
      </div>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">


      <!-- START THE FEATURETTES -->


      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Soil Investigation</h2>
          <p class="lead">We offer a comprehensive coverage of Geotechnical Investigation works in both soil and rock, planning and designing package for instrumentation works in structure and building development, reclamation and tunneling projects, inclusive of manual type and real time automatic instrumentation systems, together with alarm via GSM Mobile.</p>
          <p><a href="<%= services_soil_investigation_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" src="assets/sample3.png" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive" src="assets/sample3.png" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Geotechnical Instrumentation and Monitoring Works</h2>
          <p class="lead">We provides Geotechnical Instrumentation from Inclinometer System, Vibration and Noise Monitoring, Recharge well, to Tiltmeter System. We also provide automatic monitoring system  to monitor the data given from the instruments to analyze condition of the soil or structures.</p>
          <p><a href="<%= services_geotechnical_monitoring_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Instrumentation Sales and Distribution</span></h2>
          <p class="lead">We are the only official itmsoil distributor in Singapore. itmsoil specializes in the design, development, manufacture, and installation of a wide range of geotechnical and structural instrumentation, which embody the highest standards of engineering with the latest technology and an accredited quality control system to achieve maximum reliability and long term performance.</p>
          <p><a href="<%= services_instrumentation_sales_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" src="assets/sample3.png" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

            <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="assets/logo-small.jpg" data-src="holder.js/300x300" alt="Generic placeholder image">
          <h2>About Us</h2>
          <p>We are specializing in Geotechnical Engineering with a vast experiences for more than 10 years in the industry. It was incorporated in June 29th, 2001.</p>
          <p><a href="<%= company_profile_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="assets/news-home.jpg" data-src="holder.js/300x300" alt="Generic placeholder image">
          <h2>News</h2>
          <p>GeoLS Pte Ltd has become one of the flagship in Geotechnical Engineering. We are certified with ISO 9001 for our safety workplace.</p>
          <p><a href="<%= news_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="assets/contacts.jpg" data-src="holder.js/300x300" alt="Generic placeholder image">
          <h2>Contact Us</h2>
          <p>Please do not hesitate to contact us if you have any enquiry by telephone or email. Please visit our Contact page for more detail.</p>
          <p><a href="<%= contact_path %>" class="btn btn-warning">Read More &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

      </div>


    </div><!-- /.container -->
  </body>

app/views/static_pages/news.html.erb
<% provide(:title, 'News') %>

<br />

	<h1>News</h1>

	<div id="banner">

        <img src= <%= asset_path 'news_banner.jpg' %> />

	</div>

    <p>Please click the link below to see the content.</p>



<div id="accordion-news" class="accordion">


    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" href="#collapseTwo" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
            26/02/2013 - Awarded for Instrumentation and Monitoring Works Contract
            </a>
        </div>
     
        <div id="collapseTwo" class="accordion-body collapse in" style=" height: auto;">
            <div class="accordion-inner"> Awarded for Instrumentation and Monitoring Works Contract.
            </div>
        </div>

    </div>


    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" href="#collapseOne" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
            09/02/2013 - Happy Chinese New Year!
            </a>
        </div>
     
        <div id="collapseOne" class="accordion-body collapse in" style=" height: auto;">
            <div class="accordion-inner"> Happy Chinese Lunar Year! Wishing you a prosperous year.
            </div>
        </div>

    </div>


    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" href="#collapseTwo" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
            01/01/2013 - Merry Christmas and Happy New Year!
            </a>
        </div>
     
        <div id="collapseTwo" class="accordion-body collapse in" style=" height: auto;">
            <div class="accordion-inner"> Merry Christmas and Happy New year from all our staffs to our clients and suppliers.
            </div>
        </div>

    </div>


    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" href="#collapseThree" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
            06/06/2012 - Awarded for Soil Investigation Contract
            </a>
        </div>
     
        <div id="collapseThree" class="accordion-body collapse in" style=" height: auto;">
            <div class="accordion-inner"> 
                Awarded for Soil Investigation Contract.
            </div>
        </div>

    </div>


	<div class="accordion-group">
		<div class="accordion-heading">
    		<a class="accordion-toggle" href="#collapseFour" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
    		06/06/2012 - Awarded for Soil Investigation Contract
    		</a>
		</div>
     
    	<div id="collapseFour" class="accordion-body collapse in" style=" height: auto;">
    		<div class="accordion-inner"> 
                Awarded for Soil Investigation Contract.
    		</div>
    	</div>

    </div>

    <div class="accordion-group"</div>
		<div class="accordion-heading" >
    		<a class="accordion-toggle" href="#collapseFive" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
    		27/05/2012 - bizSAFE Star Certification
    		</a>
		</div>
     
    	<div id="collapseFive" class="accordion-body collapse in" style=" height: auto;">
    		<div class="accordion-inner"> GeoLS Pte Ltd has been awarded with bizSAFE Star certificate.
    		</div>
    	</div>

    </div>

    <div class="accordion-group"</div>
		<div class="accordion-heading" >
    		<a class="accordion-toggle" href="#collapseSix" data-toggle="collapse" data-parent="#accordion-news" style="font-weight: bold">
    		15/05/2012 - GeoLS Pte Ltd New Website
    		</a>
		</div>
     
    	<div id="collapseSix" class="accordion-body collapse in" style=" height: auto;">
    		<div class="accordion-inner"> GeoLS have launched its premier stand alone website which can be accessed in www.geols.com.sg. The website is one of GeoLS' way promote its services and become the biggest in the industry. The website provides detail explanation of all the services. It also provide a picture gallery of the geotechnical instrumentation including the data sheets of each instrument. We hope this website serves its purposes to our users and clients. We can be reached from the Contact page which have the inquiry form, which we monitor daily. Thank you.
    		</div>
    	</div>

    </div>
</div>